name: Zenn Content Check

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  zenn-content-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: List articles
        run: npm run list:articles

      - name: List books
        run: npm run list:books
